# Generated by Django 2.2.5 on 2020-01-30 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csa_app', '0004_auto_20200126_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form2_contr_num', models.PositiveIntegerField(default=None, null=True)),
                ('form2_contr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('form2_vendor_number', models.PositiveIntegerField(default=None, null=True)),
                ('form2_vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('form2_validity_start', models.DateTimeField(null=True)),
                ('form2_validity_end', models.DateTimeField(null=True)),
                ('form2_POrg', models.CharField(blank=True, max_length=50, null=True)),
                ('form2_PGrp', models.CharField(blank=True, max_length=50, null=True)),
                ('form2_target_value', models.PositiveIntegerField(default=None, null=True)),
                ('form2_currency', models.CharField(blank=True, max_length=20, null=True)),
                ('form2_payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('form2_reasons_for_outside', models.CharField(blank=True, max_length=100, null=True)),
                ('form2_setup_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='csa_app.Setup')),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
